config/routes.rb
Rails.application.routes.draw do
  get   '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'
  namespace :admin do
    resources :users
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tasks#index'
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/omotenashi_mobule.rb
# models/concerns/配下にはmodelで共通で利用するようなmoduleを定義する。
module OmotenashiMobule
  extend ActiveSupport::Concern

  included do
  end

  module ClassMethods
    def kokoro
      puts 'foo'
    end
  end

  def service
    puts 'bar'
  end
end

app/models/task.rb
class Task < ApplicationRecord
  include OmotenashiMobule

  # Action Storageを利用する準備ができたので、画像ファイルを添付できるようにします。
  # 1つのタスクに1つの画像が紐づけます。また画像は:imageで呼ぶことができるようになります。
  has_one_attached :image


  belongs_to :user
  # before_validation :set_nameless_name
  validates :name, presence: true, length: { maximum: 30 }
  validate :validate_name_not_including_comma



  private

  # def set_nameless_name
  #   self.name = "名前なし" if self.name.blank?
  # end

  def validate_name_not_including_comma
    # &.(ぼっち記号はnullだったときには処理をSKIPするという意味がある。)
    errors.add(:name, 'にカンマを含めることはできません') if name&.include?(',')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks
  has_secure_password

  # 検証
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :update, :destroy, :edit]
  before_action :require_admin
  
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました"
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :new
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end

  def require_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ヘルパーから読み出すことができる。
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_actionをskipするのです。
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました。'
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_task, only:[:show, :edit, :update, :destroy]

  # 一覧表示
  def index
    # @tasks = current_user.tasks
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).page(params[:page])
    # kaminariの表示件数のdefaultを変更するときはpreメソッドを利用するといい。
    # @tasks = @q.result(distinct: true).page(params[:page]).per(50)
  end

  # 詳細
  def show
    # @task = Task.find_by(id: params[:id])
    # @task = current_user.tasks.find_by(id: params[:id])
  end

  # 新規登録
  def new
    @task = current_user.tasks.new
  end

  # 編集
  def edit
    # @task = Task.find_by(id: params[:id])
    # @task = current_user.tasks.find_by(id: params[:id])
  end

  # 登録処理
  def create
    # @task = Task.new(task_params)
    # task_params.mergeメソッドを利用してcurrent_user.idを追加します。)
    @task = Task.new(task_params.merge(user_id: current_user.id))
    # @task = current_user.tasks.new(task_params)
    # @task.save! # セーブに失敗したらエラーを返す
    if @task.save
      TaskMailer.creation_email(@task).deliver_now
      SampleJob.perform_later(@task, "ここは非同期でいくぞー")
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else
      # エラーの場合は、再度NEWのフォーム画面を表示
      render :new
    end
  end

  # 更新機能
  def update
    @task.update!(task_params)
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を更新しました。"
  end

  def destroy
    @task.destroy
    # AJAXを利用する場合はredirect_toではなくheadメソッドを利用してレスポンスなしでもstatus 204が返る（成功と判断）※ 記述しなくてもOKだけどわかりやすくするために明記
    head :no_content
  end

  # def destroy
  #   task = current_user.tasks.find_by(id: params[:id])
  #   ActiveRecord::Base.transaction do
  #     task.destroy!
  #   end
  #   redirect_to tasks_url, notice: "タスク「#{task.name}」を削除しました。"
  # rescue => e
  #   # エラーハンドリング
  #   puts "#{e.class} : #{e.message}"
  # end

  private

  def task_params
    params.require(:task).permit(:name, :description, :image)
  end

  def find_task
    @task = current_user.tasks.find_by(id: params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation.alert.alert-danger
    - user.errors.full_messages.each do |message|
      li= message

= form_with model: [:admin, user], local: true do |f|
  .form-group
    = f.label :name, '名前'
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email, 'メールアドレス'
    = f.text_field :email, class: 'form-control'
  .form-check
    = f.label :admin, class: 'form-check-label user__checkbox--input' do
      = f.check_box :admin, class: 'form-check-input'
      | 管理者権限
  .form-group
    = f.label :password, 'パスワード'
    = f.password_field :password, class: 'form-control'
  .form-group
    = f.label :password_confirmation, 'パスワード(確認)'
    = f.password_field :password_confirmation, class: 'form-control'
  = f.submit '登録する', class: 'btn btn-primary'

app/views/admin/users/edit.html.slim
h1 ユーザー編集

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

== render 'form', user: @user

app/views/admin/users/index.html.slim
h1 ユーザー一覧

= link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= User.human_attribute_name(:name)
      th= User.human_attribute_name(:email)
      th= User.human_attribute_name(:admin)
      th= User.human_attribute_name(:created_ad)
      th= User.human_attribute_name(:updated_at)
      th
    tbody
      - @users.each do |user|
        tr
          td= link_to user.name, admin_user_path(user)
          td= user.email
          td= user.admin? ? 'あり' : 'なし'
          td= user.created_at
          td= user.updated_at
          td
            = link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
            = link_to '削除', admin_user_path(user), method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか。" }, class: 'btn btn-danger mr-3'

app/views/admin/users/new.html.slim
h1 ユーザー登録

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'

== render 'form', user: @user

app/views/admin/users/show.html.slim
h1 ユーザー詳細

.nav.justify-content-end
  = link_to '一覧', admin_users_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:id)
      td= @user.id
    tr
      th= User.human_attribute_name(:name)
      td= @user.name
    tr
      th= User.human_attribute_name(:email)
      td= @user.email
    tr
      th= User.human_attribute_name(:admin)
      td= @user.admin? ? 'あり' : 'なし'
    tr
      th= User.human_attribute_name(:created_at)
      td= @user.created_at
    tr
      th= User.human_attribute_name(:updated_at)
      td= @user.updated_at

= link_to '編集', edit_admin_user_path(@user), class: 'btn btn-primary mr-3'
= link_to '削除', admin_user_path(@user), method: :delete, data: { confirm: "ユーザー「#{@user.name}」を削除します。よろしいですか。" }, class: 'btn btn-danger mr-3'

app/views/layouts/_offline.html.slim
.offline-content オフラインです。ネットワークにつながっていません。

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TaskleafSandbox
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .offline
      == render "layouts/offline"
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Taskleaf

      ul.navbar-nav.ml-auto
        - if current_user
          li.nav-item= link_to 'タスク一覧', tasks_path, class: 'nav-link'
          - if current_user.admin?
            li.nav-item= link_to 'ユーザー一覧', admin_users_path, class: 'nav-link'
          li.nav-item= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'
        - else
          li.nav-item= link_to 'ログイン', login_path, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield

app/views/tasks/__form.html.slim
= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_area :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 7, class: 'form-control', id: 'task_description'
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/_form.html.slim
- if !task.nil? && task.errors.present?
  ul#error_explanation.alert.alert-danger
    - task.errors.full_messages.each do |message|
      li= message

/ local: trueを指定する理由はform_withはdefaultでAjaxを利用するのを無効にするため。
= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_area :name, class: 'form-control', id: 'task-name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 7, class: 'form-control', id: 'task-description'
  .form-group
    = f.label :image
    = f.file_field :image, class: `form-control`
  = f.submit nil, class: 'btn btn-primary'

p(style="color:red") すみません。絵文字は利用できません。

app/views/tasks/edit.html.slim
h1 タスクの編集

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

== render "form", task: @task

app/views/tasks/index.html.slim
h1 タスク表示

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont, '名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control'
  .form-group.row
    = f.label :created_at_gteq, '登録日時', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control'
  .form-group
    = f.submit class: 'btn btn-outline-primary'


.hogehoge
  p
    = link_to "Yahooへ", "https://yahoo.co.jp/", target: '_blank'
  p
    = link_to "Googleへ", "https://google.com/", target: '_blank'
  / a href="https://google.com" target="_blank"
  /   | GOOGLEへ

.mb-3
  = link_to '新規登録', new_task_path, class: 'btn btn-primary'


.mb-3
  = paginate @tasks
  = page_entries_info @tasks


table.table.table-hover
  thead.thead-default
    tr
      th= sort_link(@q, :name, default_order: :desc)
      th= sort_link(@q, :created_at, default_order: :desc)
      / th= Task.human_attribute_name(:name)
      / th= Task.human_attribute_name(:created_at)
      th
    tbody
      - @tasks.each do |task|
        tr
          td= link_to task.name, task_path(task)
          td= task.created_at
          td
            = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
            = link_to '削除', task, method: :delete, remote: true, data: { confirm: "タスク 「#{task.name}」を削除します。よろしいですか。" }, class: 'btn btn-danger delete'

app/views/tasks/new.html.slim
h1 タスクの新規登録

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

== render "form", task: @task

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

.task-dashbord
  table.table.table-hover
    tbody
      tr
        th= Task.human_attribute_name(:id)
        td= @task.id
      tr
        th= Task.human_attribute_name(:name)
        td= @task.name
      tr
        th= Task.human_attribute_name(:description)
        / td= simple_format(@task.description, {}, sanitize: false, wrapper_tag: "div")
        / td= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div")
        / td= auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div"))
        td= raw Rinku.auto_link(simple_format(h(@task.description)), :all, 'target="_blank"')
      tr
        th= Task.human_attribute_name(:image)
        td= image_tag @task.image, :width => "600" if @task.image.attached?
      tr
        th= Task.human_attribute_name(:created_at)
        td= @task.created_at
      tr
        th= Task.human_attribute_name(:updated_at)
        td= @task.updated_at

  = link_to '編集', edit_task_path(@task), class: 'btn btn-primary mr-3'